# Generated by Django 2.2.1 on 2019-07-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_numbers', models.TextField(blank=True, null=True)),
                ('stop_headsign', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bus_stops',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StopsInfo',
            fields=[
                ('stop_lat', models.FloatField(blank=True, null=True)),
                ('stop_lon', models.FloatField(blank=True, null=True)),
                ('stop_id', models.TextField(blank=True, primary_key=True, serialize=False)),
                ('actual_stop_id', models.IntegerField(blank=True, null=True)),
                ('stop_name', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'stops_info',
                'managed': False,
            },
        ),
    ]
