# Generated by Django 2.2.1 on 2019-07-08 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStops',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.TextField()),
                ('bus_numbers', models.TextField()),
                ('stop_headsign', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='StopsInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_lat', models.FloatField()),
                ('stop_lon', models.FloatField()),
                ('stop_id', models.TextField()),
                ('actual_stop_id', models.IntegerField()),
                ('stop_name', models.TextField()),
                ('routes', models.ManyToManyField(to='map.BusStops')),
            ],
        ),
    ]
