# Generated by Django 2.2.1 on 2019-07-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_auto_20190711_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holidays',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('public_holiday', models.BooleanField(default=False)),
                ('primary_holiday', models.BooleanField(default=False)),
                ('secondary_holiday', models.BooleanField(default=False)),
            ],
        )
    ]
