# Generated by Django 2.2.2 on 2019-08-06 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20190718_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stopsinfo',
            old_name='stop_lon',
            new_name='stop_lng',
        ),
    ]
